# Generated by Django 3.0.6 on 2020-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='цена')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
            ],
        ),
    ]
